In [57]:
import pandas as pd
import numpy as np

In [58]:
from google.colab import files
uploaded = files.upload()

Saving Supply_Chain_Dataset_500_Rows_20_Columns.xlsx to Supply_Chain_Dataset_500_Rows_20_Columns (2).xlsx

In [59]:
df = pd.read_excel("Supply_Chain_Dataset_500_Rows_20_Columns.xlsx")

In [60]:
df.head()

,Order_ID,Product_ID,Product_Name,Category,Supplier,Warehouse,Order_Date,Delivery_Date,Quantity,Unit_Price,Total_Amount,Transport_Mode,Delivery_Status,Customer_City,State,Payment_Status,Inventory_Level,Return_Flag,Priority,Employee_ID
0,O0001,P103,Keyboard,Accessories,NaN,Bangalore,2026-04-05,2026-04-10,88.0,1200.0,105600.0,Road,Delayed,Pune,Telangana,Paid,192,No,Medium,E129
1,O0002,P101,Laptop,Electronics,Canon,NaN,2026-01-06,2026-01-11,75.0,50000.0,3750000.0,Sea,delivered,Hyderabad,Karnataka,Pending,367,No,Medium,E150
2,O0003,P104,Monitor,Electronics,HP,NaN,2026-03-21,2026-03-26,29.0,12000.0,348000.0,Sea,delivered,Hyderabad,Karnataka,Paid,331,Yes,Medium,E117
3,O0004,P105,Printer,Office,HP,Pune,2026-06-06,2026-06-11,100.0,15000.0,1500000.0,Road,Delivered,Coimbatore,Maharashtra,Paid,405,No,High,E139
4,O0005,P103,Keyboard,Accessories,Samsung,Hyderabad,2026-05-15,2026-05-20,86.0,1200.0,103200.0,Air,Pending,Hyderabad,Karnataka,Paid,260,No,High,E144

In [61]:
df.tail()

,Order_ID,Product_ID,Product_Name,Category,Supplier,Warehouse,Order_Date,Delivery_Date,Quantity,Unit_Price,Total_Amount,Transport_Mode,Delivery_Status,Customer_City,State,Payment_Status,Inventory_Level,Return_Flag,Priority,Employee_ID
496,O0497,P101,Laptop,Electronics,Canon,Pune,2026-06-22,2026-06-27,92.0,50000.0,4600000.0,Rail,Delivered,Coimbatore,Karnataka,Paid,172,No,Medium,E128
497,O0498,P101,Laptop,Electronics,Dell,NaN,2026-04-24,2026-04-29,43.0,50000.0,2150000.0,Rail,In Transit,Pune,Telangana,Pending,368,No,Medium,E117
498,O0499,P101,Laptop,Electronics,Canon,Hyderabad,2026-04-09,2026-04-14,13.0,50000.0,650000.0,Sea,delivered,Coimbatore,Tamil Nadu,Paid,186,No,High,E128
499,O0500,P102,Mouse,Accessories,Dell,Chennai,2026-02-28,2026-03-05,94.0,700.0,65800.0,Rail,delivered,Chennai,Tamil Nadu,Paid,132,Yes,Low,E129
500,O0009,P101,Laptop,Electronics,HP,Bangalore,2026-03-31,2026-04-05,4.0,50000.0,200000.0,Sea,delivered,Pune,Tamil Nadu,Paid,54,No,Low,E128

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 501 entries, 0 to 500
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         501 non-null    object
 1   Product_ID       501 non-null    object
 2   Product_Name     501 non-null    object
 3   Category         501 non-null    object
 4   Supplier         393 non-null    object
 5   Warehouse        397 non-null    object
 6   Order_Date       501 non-null    object
 7   Delivery_Date    485 non-null    object
 8   Quantity         484 non-null    float64
 9   Unit_Price       488 non-null    float64
 10  Total_Amount     471 non-null    float64
 11  Transport_Mode   501 non-null    object
 12  Delivery_Status  501 non-null    object
 13  Customer_City    501 non-null    object
 14  State            501 non-null    object
 15  Payment_Status   501 non-null    object
 16  Inventory_Level  501 non-null    int64
 17  Return_Flag      501 non-null    object
 18  Priority         501 non-null    object
 19  Employee_ID      501 non-null    object
dtypes: float64(3), int64(1), object(16)
memory usage: 78.4+ KB

In [63]:
df.describe()

         Quantity    Unit_Price  Total_Amount  Inventory_Level
count  484.000000    488.000000  4.710000e+02       501.000000
mean    49.206612  15075.409836  7.470386e+05       261.459082
std     27.817928  17177.081390  1.027361e+06       144.761337
min      1.000000    700.000000  7.000000e+02         0.000000
25%     26.750000   1200.000000  5.335000e+04       142.000000
50%     48.000000  12000.000000  3.600000e+05       266.000000
75%     72.000000  15000.000000  1.011000e+06       395.000000
max    100.000000  50000.000000  4.950000e+06       500.000000

In [64]:
df.isnull().sum()

Order_ID             0
Product_ID           0
Product_Name         0
Category             0
Supplier           108
Warehouse          104
Order_Date           0
Delivery_Date       16
Quantity            17
Unit_Price          13
Total_Amount        30
Transport_Mode       0
Delivery_Status      0
Customer_City        0
State                0
Payment_Status       0
Inventory_Level      0
Return_Flag          0
Priority             0
Employee_ID          0
dtype: int64

In [65]:
df.drop_duplicates(inplace=True)

In [66]:
df.duplicated().sum()

np.int64(0)

In [67]:
df["Quantity"] = df["Quantity"].fillna(df["Quantity"].median())

In [68]:
df["Unit_Price"] = df["Unit_Price"].fillna(df["Unit_Price"].mean())

In [69]:
df["Supplier"] = df["Supplier"].fillna("Unknown")

In [70]:
df["Warehouse"] = df["Warehouse"].fillna(df["Warehouse"].mode()[0])

In [71]:
df["Delivery_Date"] = df["Delivery_Date"].fillna(df["Order_Date"])

In [72]:
df["Total_Amount"] = df["Total_Amount"].fillna(
    df["Quantity"] * df["Unit_Price"]
)

In [73]:
df.isnull().sum()

Order_ID           0
Product_ID         0
Product_Name       0
Category           0
Supplier           0
Warehouse          0
Order_Date         0
Delivery_Date      0
Quantity           0
Unit_Price         0
Total_Amount       0
Transport_Mode     0
Delivery_Status    0
Customer_City      0
State              0
Payment_Status     0
Inventory_Level    0
Return_Flag        0
Priority           0
Employee_ID        0
dtype: int64

In [74]:
text_columns = df.select_dtypes(include="object").columns

for col in text_columns:
    df[col] = df[col].str.strip()

In [75]:
df["Product_Name"] = df["Product_Name"].str.title()
df["Supplier"] = df["Supplier"].str.title()
df["Transport_Mode"] = df["Transport_Mode"].str.title()
df["Delivery_Status"] = df["Delivery_Status"].str.upper()
df["Payment_Status"] = df["Payment_Status"].str.upper()

In [76]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"])
df["Delivery_Date"] = pd.to_datetime(df["Delivery_Date"])

In [77]:
df.rename(columns={
    "Unit_Price": "Price_Per_Unit",
    "Employee_ID": "Manager_ID"
}, inplace=True)

In [78]:
pending = df[df["Payment_Status"] == "PENDING"]
pending.head()

,Order_ID,Product_ID,Product_Name,Category,Supplier,Warehouse,Order_Date,Delivery_Date,Quantity,Price_Per_Unit,Total_Amount,Transport_Mode,Delivery_Status,Customer_City,State,Payment_Status,Inventory_Level,Return_Flag,Priority,Manager_ID
1,O0002,P101,Laptop,Electronics,Canon,Pune,2026-01-06,2026-01-11,75.0,50000.0,3750000.0,Sea,DELIVERED,Hyderabad,Karnataka,PENDING,367,No,Medium,E150
9,O0010,P103,Keyboard,Accessories,Samsung,Pune,2026-03-13,2026-03-18,59.0,1200.0,70800.0,Rail,DELIVERED,Chennai,Telangana,PENDING,448,No,Low,E123
12,O0013,P101,Laptop,Electronics,Unknown,Bangalore,2026-01-01,2026-01-06,29.0,50000.0,1450000.0,Air,DELIVERED,Coimbatore,Karnataka,PENDING,24,No,Low,E131
14,O0015,P104,Monitor,Electronics,Hp,Pune,2026-02-06,2026-02-11,96.0,12000.0,1152000.0,Rail,DELIVERED,Chennai,Karnataka,PENDING,436,No,Medium,E144
18,O0019,P105,Printer,Office,Samsung,Chennai,2026-02-01,2026-02-06,62.0,15000.0,930000.0,Sea,DELIVERED,Chennai,Karnataka,PENDING,180,No,High,E105

In [79]:
high = df[df["Priority"] == "High"]
high.head()

,Order_ID,Product_ID,Product_Name,Category,Supplier,Warehouse,Order_Date,Delivery_Date,Quantity,Price_Per_Unit,Total_Amount,Transport_Mode,Delivery_Status,Customer_City,State,Payment_Status,Inventory_Level,Return_Flag,Priority,Manager_ID
3,O0004,P105,Printer,Office,Hp,Pune,2026-06-06,2026-06-11,100.0,15000.0,1500000.0,Road,DELIVERED,Coimbatore,Maharashtra,PAID,405,No,High,E139
4,O0005,P103,Keyboard,Accessories,Samsung,Hyderabad,2026-05-15,2026-05-20,86.0,1200.0,103200.0,Air,PENDING,Hyderabad,Karnataka,PAID,260,No,High,E144
6,O0007,P105,Printer,Office,Unknown,Pune,2026-04-16,2026-04-21,24.0,15000.0,360000.0,Road,DELAYED,Coimbatore,Telangana,PAID,410,Yes,High,E105
7,O0008,P105,Printer,Office,Unknown,Bangalore,2026-01-03,2026-01-08,69.0,15000.0,1035000.0,Rail,IN TRANSIT,Pune,Maharashtra,PARTIAL,497,Yes,High,E118
11,O0012,P105,Printer,Office,Samsung,Pune,2026-02-10,2026-02-15,17.0,15000.0,255000.0,Air,DELAYED,Pune,Telangana,PAID,341,No,High,E124

In [80]:
df.nunique()

Order_ID           500
Product_ID           5
Product_Name         5
Category             3
Supplier             5
Warehouse            4
Order_Date         165
Delivery_Date      166
Quantity            99
Price_Per_Unit       6
Total_Amount       295
Transport_Mode       4
Delivery_Status      4
Customer_City        4
State                4
Payment_Status       3
Inventory_Level    322
Return_Flag          2
Priority             3
Manager_ID          50
dtype: int64

In [81]:
df["Product_Name"].value_counts()

Product_Name
Printer     110
Monitor     107
Mouse       101
Keyboard     92
Laptop       90
Name: count, dtype: int64

In [82]:
df["Delivery_Status"].value_counts()

Delivery_Status
DELIVERED     201
PENDING       108
DELAYED       100
IN TRANSIT     91
Name: count, dtype: int64

In [83]:
df.sort_values(by="Total_Amount", ascending=False)

,Order_ID,Product_ID,Product_Name,Category,Supplier,Warehouse,Order_Date,Delivery_Date,Quantity,Price_Per_Unit,Total_Amount,Transport_Mode,Delivery_Status,Customer_City,State,Payment_Status,Inventory_Level,Return_Flag,Priority,Manager_ID
13,O0014,P101,Laptop,Electronics,Canon,Hyderabad,2026-05-26,2026-05-31,99.0,50000.0,4950000.0,Road,PENDING,Chennai,Tamil Nadu,PARTIAL,45,No,High,E123
102,O0103,P101,Laptop,Electronics,Canon,Pune,2026-04-13,2026-04-18,97.0,50000.0,4850000.0,Air,DELIVERED,Pune,Karnataka,PENDING,63,No,Low,E148
205,O0206,P101,Laptop,Electronics,Samsung,Pune,2026-05-25,2026-05-30,97.0,50000.0,4850000.0,Sea,DELIVERED,Pune,Telangana,PAID,331,No,Medium,E144
34,O0035,P101,Laptop,Electronics,Unknown,Pune,2026-04-07,2026-04-12,97.0,50000.0,4850000.0,Rail,DELAYED,Coimbatore,Karnataka,PENDING,22,No,High,E128
496,O0497,P101,Laptop,Electronics,Canon,Pune,2026-06-22,2026-06-27,92.0,50000.0,4600000.0,Rail,DELIVERED,Coimbatore,Karnataka,PAID,172,No,Medium,E128
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,O0153,P102,Mouse,Accessories,Canon,Pune,2026-04-23,2026-04-28,3.0,700.0,2100.0,Road,DELIVERED,Pune,Karnataka,PENDING,441,Yes,Medium,E122
172,O0173,P102,Mouse,Accessories,Hp,Bangalore,2026-02-09,2026-02-14,3.0,700.0,2100.0,Sea,IN TRANSIT,Coimbatore,Maharashtra,PAID,384,Yes,Medium,E125
237,O0238,P103,Keyboard,Accessories,Canon,Pune,2026-06-17,2026-06-22,1.0,1200.0,1200.0,Sea,DELIVERED,Pune,Telangana,PARTIAL,127,Yes,Low,E129
194,O0195,P103,Keyboard,Accessories,Unknown,Pune,2026-05-13,2026-05-18,1.0,1200.0,1200.0,Rail,DELIVERED,Pune,Maharashtra,PENDING,20,Yes,Low,E105
250,O0251,P102,Mouse,Accessories,Unknown,Bangalore,2026-05-12,2026-05-17,1.0,700.0,700.0,Sea,DELIVERED,Chennai,Tamil Nadu,PAID,419,Yes,Medium,E149

In [84]:
df.to_excel("Cleaned_Supply_Chain_Dataset.xlsx", index=False)

In [85]:
from google.colab import files
files.download("Cleaned_Supply_Chain_Dataset.xlsx")